### ISSUE TITLE
如何添加自己的词向量？

### ISSUE THREAD

**Issue by Shenxin0925** [v-mipeng/LexiconAugmentedNER#41]
我用word2vec训练了50维的词向量，更改路径运行后发生了这个报错：
Traceback (most recent call last):
  File "main.py", line 526, in <module>
    data.build_word_pretrain_emb(char_emb)
  File "/home/admin/lc/各种模型/融合词典的中文分词/LexiconAugmentedNER-master/utils/data.py", line 262, in build_word_pretrain_emb
    self.pretrain_word_embedding, self.word_emb_dim = build_pretrain_embedding(emb_path, self.word_alphabet, self.word_emb_dim, self.norm_word_emb)
  File "/home/admin/lc/各种模型/融合词典的中文分词/LexiconAugmentedNER-master/utils/functions.py", line 188, in build_pretrain_embedding
    embedd_dict, embedd_dim = load_pretrain_emb(embedding_path)
  File "/home/admin/lc/各种模型/融合词典的中文分词/LexiconAugmentedNER-master/utils/functions.py", line 233, in load_pretrain_emb
    assert (embedd_dim + 1 == len(tokens))
AssertionError

请问这是什么原因？

**Comment by SomeoneNotLikeYou** [comment]
你是要替换某个词向量 还是添加额外的向量

**Comment by Kakaiero** [comment]
请问如果是添加额外的向量呢

**Comment by 550952213** [comment]
老哥你解决了吗

**Comment by Kakaiero** [comment]
没啊，愁的很




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "v-mipeng/LexiconAugmentedNER"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月21日(星期一) 晚上9:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [v-mipeng/LexiconAugmentedNER] 如何添加自己的词向量？ (#41)





 
老哥你解决了吗
